# Generated by Django 3.0.6 on 2020-10-02 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='pass_code',
            field=models.CharField(default='', max_length=6),
        ),
    ]
